// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How recently a file must have changed to be shown (SEA-6).
 */
export type Changed = "pastWeek" | "pastMonth" | "pastYear";
