// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PassageHit } from "./PassageHit";

export type FileHit = { name: string, folder: string, 
/**
 * How many files share this exact content (1 means no copies).
 */
copies: number, passages: Array<PassageHit>, };
