// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What came of opening or revealing a result's file.
 */
export type FileAction = "done" | "missing";
