// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A folder the user chose. The path is shown, never sent back.
 */
export type Folder = { id: number, path: string, };
