// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderState } from "./FolderState";

/**
 * A folder the user chose, with what indexing knows of it.
 */
export type FolderStatus = { id: number, path: string, state: FolderState, };
