// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the index would go, for the user to confirm (APP-7).
 */
export type IndexFolderChoice = { 
/**
 * The folder of its own the index would be kept in.
 */
path: string, 
/**
 * The cloud service that copies that folder, if one does (PRIV-4).
 */
syncedBy: string | null, };
