// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether meaning search is available.
 */
export type Meaning = { "state": "loading" } | { "state": "ready" } | { "state": "off", reason: string, };
