// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotIndexed = { name: string, folder: string, reason: string, 
/**
 * The reason's stable code, such as "needs-ocr", for counting by cause.
 */
code: string, 
/**
 * True when reading failed; false when the file was skipped by a rule.
 */
failed: boolean, 
/**
 * True when reading failed too often: it is not tried again until the
 * user asks for a retry.
 */
parked: boolean, };
