// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotIndexed = { name: string, folder: string, reason: string, 
/**
 * True when reading failed; false when the file was skipped by a rule.
 */
failed: boolean, };
