// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FoundBy } from "./FoundBy";
import type { Span } from "./Span";

export type PassageHit = { 
/**
 * The id to preview, open or reveal this passage's file with.
 */
id: number, location: string, 
/**
 * The matching words, marked; shown as plain text only.
 */
snippet: Array<Span>, found: FoundBy, };
