// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of the processor indexing may use (IDX-5).
 */
export type ResourceMode = "light" | "balanced" | "fast";
