// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Changed } from "./Changed";
import type { FileKind } from "./FileKind";

/**
 * What a search may return (SEA-6). The folder is named by its id: the
 * interface never sends a path.
 */
export type SearchFilter = { folder: number | null, kind: FileKind | null, changed: Changed | null, };
