// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileHit } from "./FileHit";

export type SearchResponse = { 
/**
 * One entry per file, best first, its passages beneath it (SEA-3).
 */
files: Array<FileHit>, 
/**
 * What to know about these results, in plain words.
 */
notes: Array<string>, elapsedMs: number, };
