// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Folder } from "./Folder";

/**
 * The settings the interface shows and changes (APP-3).
 */
export type SettingsView = { 
/**
 * Folders inside the chosen ones that are left out.
 */
excludedFolders: Array<Folder>, 
/**
 * Names of files and folders that are left out.
 */
patterns: Array<string>, 
/**
 * The patterns a new install starts with.
 */
defaultPatterns: Array<string>, 
/**
 * Where the index is stored (COV-3).
 */
dataFolder: string, 
/**
 * The size of the index on disk, in bytes.
 */
indexBytes: number, };
