// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Folder } from "./Folder";
import type { ResourceMode } from "./ResourceMode";
import type { TextSize } from "./TextSize";
import type { Theme } from "./Theme";

/**
 * The settings the interface shows and changes (APP-3).
 */
export type SettingsView = { 
/**
 * Folders inside the chosen ones that are left out.
 */
excludedFolders: Array<Folder>, 
/**
 * Names of files and folders that are left out.
 */
patterns: Array<string>, 
/**
 * The patterns a new install starts with.
 */
defaultPatterns: Array<string>, 
/**
 * Where the index is stored (COV-3).
 */
dataFolder: string, 
/**
 * The size of the index on disk, in bytes.
 */
indexBytes: number, 
/**
 * Logs also record file paths and error details.
 */
detailedLogs: boolean, version: string, resourceMode: ResourceMode, 
/**
 * The cloud service that copies the data folder, if one does (PRIV-4).
 */
dataSyncedBy: string | null, theme: Theme, textSize: TextSize, 
/**
 * Larger files are skipped (SRC-7).
 */
maxFileMb: number, 
/**
 * Pages past this many are not read from a PDF.
 */
maxPages: number, 
/**
 * Indexing waits while the computer runs on battery (IDX-9).
 */
pauseOnBattery: boolean, };
