// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A piece of text; `marked` pieces are the words that matched.
 */
export type Span = { text: string, marked: boolean, };
