// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Folder } from "./Folder";
import type { Meaning } from "./Meaning";
import type { NotIndexed } from "./NotIndexed";
import type { Work } from "./Work";

/**
 * Everything the interface shows about the index and its work.
 */
export type Status = { folders: Array<Folder>, 
/**
 * What indexing is doing right now, if anything.
 */
work: Work | null, files: number, passages: number, searchableByMeaning: number, meaning: Meaning, 
/**
 * Files that were not indexed in the last run, with why.
 */
notIndexed: Array<NotIndexed>, 
/**
 * The last thing that went wrong, in plain words.
 */
problem: string | null, };
