// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderStatus } from "./FolderStatus";
import type { Meaning } from "./Meaning";
import type { NotIndexed } from "./NotIndexed";
import type { PauseReason } from "./PauseReason";
import type { Work } from "./Work";

/**
 * Everything the interface shows about the index and its work.
 */
export type Status = { folders: Array<FolderStatus>, 
/**
 * What indexing is doing right now, if anything.
 */
work: Work | null, files: number, passages: number, searchableByMeaning: number, meaning: Meaning, 
/**
 * Files that are not in the index, with why (COV-2).
 */
notIndexed: Array<NotIndexed>, 
/**
 * The last thing that went wrong, in plain words.
 */
problem: string | null, 
/**
 * What was found at start, said once: the index or the settings were
 * damaged (spec section 8, "Index unreadable"). The interface keeps it
 * on screen until the user closes it.
 */
notice: string | null, 
/**
 * The first-launch steps are not done yet (APP-1).
 */
firstLaunch: boolean, 
/**
 * Why indexing is paused, if it is (IDX-5, RSC-3).
 */
paused: PauseReason | null, 
/**
 * When a scan of every folder last finished, in seconds since 1970.
 */
lastScanSecs: number | null, };
