// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How large the interface is drawn, on top of Windows' own scaling.
 */
export type TextSize = "normal" | "large" | "larger";
