// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Light or dark, or as Windows is set (APP-3).
 */
export type Theme = "system" | "light" | "dark";
