// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A newer version of Catchword (APP-2).
 */
export type UpdateOffer = { version: string, 
/**
 * What changed, as written for the release. Shown as plain text.
 */
notes: string, };
