// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateOffer } from "./UpdateOffer";

/**
 * Checking for updates (APP-2, ADR-24).
 */
export type Updates = { 
/**
 * This build checks for updates itself: the GitHub download. The Store
 * build is updated by Windows.
 */
inBuild: boolean, 
/**
 * The user's choice; None until asked.
 */
check: boolean | null, 
/**
 * When a check last succeeded, in seconds since 1970.
 */
lastCheckSecs: number | null, 
/**
 * A newer version, found by the last check.
 */
offer: UpdateOffer | null, };
